### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by Bia10** [jnpl95/Timelapse#2]
Hello,

First of all thank for your contribution its nice to see old style trainer for MS.

I have tested the latest commit build with VS2017 on various Pservers and there are few concerns:

Lack of stability:

The trainer randomly crashes MS without any error. This happens while botting keystrokes while using hacks like kami/item vac/fma. Its hard to say why does that happen i have yet to narrow it down a bit it might be also caused by unlimited att or no breath but that's unlikely.

Problem with map rusher:

Doesn't seem to work on maple island returns no path.
On some Pservers it doesn't work generally, when u start the path it respawn on the correct portal but then doesn't enter it and finishes the path anyways.

Some missing features:

Better keystroke emulation, currently there seem to be no option to simulate a keypress down and then release it just spams by delay.  Ability to bind hacks to keystrokes. Sometimes its nice to have hacks turnable quickly on and off. 

A safety switch to turn all SS visible hacks off again preferably bindable to a hotkey.

Ability to launch/embed/resize a MS client window into the hack window. MS window is notoriously annoying on inability to be resized by default this would be handy if you could choose at what W x H you would like to embed the client in hack app.

Regarding the hacks:

The miss godmode is missing option to decide after how many misses you should take a hit if at all.
The blink godmode is missing option to decide the time after which you should take a hit if at all.

What is the difference between instant loot items and fast loot items?? The first one is a tubi? 
The full map attack is actually not a true FMA but only very limited area.
What is the difference between uEMI and dEMI?
Wall vac/DupeX/MMC not yet implemented?

The hack i am missing:

Login:
Show pin
PinTyper
Pin Bypass
Show pic
PicTyper

Char:
MP/HP regen hacks with settings by what value at what periods.
Sit anywhere
Speedwalk
Glide/slide anywhere
Min/Max dmg
Use ammo after its reached 0
Etc explosion

Mobs:
Lemmings(mobs fall thru platforms)
FilterFaded(Boss fade)

Vacs: 
Vac right
Vac left
CSEAX
ZZ vac
Pet item vac
Gravity vac
Zero vac
Force vac
Pvac

Pointers:
Map Walls right/left/bottom/top
Map FrogJump
Map Gravity
Map JumpHeight
Map FlySpeed
Map FallSpeed
Map Friction

Mouse animation
Char animation
Char morph
Char combo count

Hardcoded client stuff:
Max drop meso value
Max damage cap
Max pdmg cap
Max mdmg cap
Max walkspeed
Max jumpheight
Turn of lightbulbs
Gravity

Beside these minor things two aspects would be great to change/implement in future:

An scriptable API lets say in Lua(easy to implement) for automation of tasks.

A better GUI system, i love the oldskool style but i hate to work with winforms and they sluggish responsives its not a proper GUI system, hard to manage, extended, bad speeds, depends on localized files .rc, etc... i think you know. So in future implementing some lightweight GUI like [Nuklear ](https://github.com/vurtun/nuklear) would be great.

Well thanks. Maybe ill have time to contribute laters.

**Comment by jnpl95** [comment]
Hi, thanks so much for your feedback. The trainer is definitely still a work in progress, I haven't made it for release yet.

Stability: 
- I've only tested it out on HeavenMS (a private server I'm running on my pc) so I haven't fixed bugs that might cause the trainer to crash on other private servers yet
- In general, I will be working on fixing stability (better loop/thread management) right after finishing up vacs/pe/rusher

Rusher: 
- For map rushing issues on other private servers, I need to test it out. Could you name a private server you have been testing out on? Just to make things easier to fix, since that shouldn't happen. 

Features: 
- In regards to emulating a keystroke, I'm not sure what you mean, could you clarify that for me? Like the Auto Buff tab allows for buffs to be cast at certain intervals (since every buff has a cooldown time afaik). 
- The ability to map hacks to keys is a great suggestion, thanks! I'll add that to my todo list (you can see the readme for the current todo list)
- Enable/Disable All hacks are in my todo list
- "Ability to launch/embed/resize a MS client window into the hack window" I'll definitely add that. For embedding the MS Client, I don't think I would want to extend the Hack's GUI. I'll probably make a window, embed MS into it, and allow users to resize/show/hide MS using that window. 

Hacks: 
- I'll add those options to Miss/Blink Godmode, thanks for the suggestion. I just assumed 7 miss godmode & infinite blink
- Instant loot shows no pickup loot animation. It's instant
- I'll change the name for Fast Loot Items. I don't know why I changed it from tubi
- I'll look into Full Map Attack's hitbox. Off the top of my head, I don't think I know how to create a true full map attack because I think the function only loads for the part of the map you're in. Think it's an MS efficiency saving measure
- Login Hacks: I'll add show pin/pic, pin/pic typer & bypass to my list
- Character Hacks: 
  I'm not sure if hp/mp regen hacks work for v83, but I'll definitely check. 
  Sit anywhere I can add, didn't think anyone would want it lol. 
  I'll add speed walk/ min max damage
  I looked for slide anywhere, but I couldn't find the hack in v83 :(
  I don't know what you mean by etc explosion hack, could you clarify that? 
  I'll look into using ammo after it reaches 0 if it is client sided & not server sided
- Mob Hacks: 
  I'll add lemmings & filter faded once I find those hacks

Vacs: 
- uEMI & dEMI are different functions but I'll remove dEMI. I haven't started on vacs as of yet
- I haven't added all those vacs you mentioned because I've never personally used those hacks (didn't think they were useful compared to dupex, mmc, spawn vac & uemi). Like I don't know in what situation gravity hack would be useful. Is there any of those vacs you mentioned that you'd particularly like to see? I'll add all those vacs to my todo list though.

Client Edits:
- Yeah I'll have to add editing Maplestory physics sometime in the future

Pointers: 
- I wish I could add all those pointers as well but as you could see from the GUI, there's no space for it. I'll probably change up the GUI and make the trainer larger to add those pointers later on. 

Scriptable API: I'll look into it when I'm finished with everything else, I don't think I'll add it as a priority at the moment because it can get complex. When I'm done with the trainer, I'll add scriptable api (which is what the advanced botting tab is for: legit botting & scripts

Better GUI: I know I hate windows form too now but I figured I'll finish this trainer up in windows form and use QT or something else for my next project.

**Comment by Bia10** [comment]
The stability problem seem to be related to two things:

The kami vac teleporting.
Changing settings of the hack while botting.

Regarding the keystrokes emulation:

Add option to hold a certain key down pressed for an amount of time and then release, wait and repeat.
Visible difference in looting. Your keystroke emulated looting loots much slower at 0ms delay then when manually holding Z or 0.

Regarding the hacks:

More options a hacker has more creative he can be don't miss any hack or any option possible. It doesn't matter that sit anywhere seem useless to you i am sure the game mechanic wont handle that well in all cases :) so in some kind of possible events sit anywhere may be of extreme value. 

Yes the FMA hits only a small rectangular area around character however i know for sure that is not the case with all skills. Some do hit every mob on the map when FMA is active this needs further research.

MP/HP regen hacks:
Well not sure about HP but pretty sure you can change the period of MP regen tick in 0.83

00A031F5: 
cmp ebx, 00002710 // original MP regen tick 10 000miliseconds

Etc explosion:
A hacker once realized that only fools would use mesos to explode as bandit rather using arrows for meso explosion this hack was long private then leaked and patched quickly :)

00505806:
db 90 90 90 90 90 90

Use ammo with zero ammount:

009516BA: 
db 90 90 90 90 90 90

009516C2: 
db 0f 89

Again as i said above its not matter of what us narrow minded fools can see as useful hack its about having all hacks possible and then brewing from them the ultimate exploitation routine :smiling_imp: 

Ill try to check my oldskool sources for more haxes or update some older ones from v0.62

Regarding pointers:
Combo count: 00BEBF98 + 3220
Char Anim: 00BEBF98 + 570

Regarding the hardcoded stuff:
Magic att cap: 00780621
Meso drop cap: 0081DAC7
Gravity?: 00AF0DE0

Regarding the embedding this is a never released never finished my personal trainer based on ati-bot:
![image](https://user-images.githubusercontent.com/2548763/48520337-8cbd5680-e870-11e8-994b-58e073d59d2c.jpeg)

Regarding the GUI if you want maximum performance and stability which is advised i would strongly lean towards either Nuclear or WxWidgets both offer superior performance to quite bloated QT. But if your good with QT then be it so :{

Please make the GUI resizable it looks terrible on oldskool win look :P

**Comment by jnpl95** [comment]
Thanks so much for this. So helpful. I'll keep this issue open to reference it until I implement everything. I'm generally reluctant to GUI changes, but I guess I got to, to make every option available.

I agree 100% that hackers should have every option available. I don't know how hard it would be to make the GUI resizable but I'll definitely look into it.  Thanks again for your feedback!
