### ISSUE TITLE
Issue faced during compilation (Newbie eager to learn)

### ISSUE THREAD

**Issue by felips113** [jnpl95/Timelapse#20]
Hi bro,

First of all, I belive this is a fantastic work and very helpful to the hack community. Thanks for your hardwork.

Understand that this project is mean for coder or experienced reverse engineer. But I am really passion to learn all these too.

I would really like to utilize what you have done and make some contribution on top of it. Frankly, I am a beginner in this area and have did a lot of research up to here. I am able to create a dll file with simple hack function by following some tutorial out there. However, I am facing some error while trying to create the dll using the source code you provided.

Really appreciate if you can provide some guide or link for me to improve. I am happy to pay for it because I am really eager to learn about this. Please let me know and give me your contact info, so we can discuss this in more detail.

Attached my log of error while doing the compilation. Thank you!!

Regards,
Ferris
[compile error.txt](https://github.com/jnpl95/Timelapse/files/6893996/compile.error.txt)

**Comment by felips113** [comment]
Hello I did further research on this and have several question that I am not able to find a solution yet. I figure out that most of the error coming from undefined namespace like System, Windows, Xml, Serialization etc.  Could you guide me on this? 

Also in HelperFunctions.h, it included Functions.h but I cant seem to locate this Functions.h in the zip file. 

Appreciate if you could provide some insight on this :)

**Comment by felips113** [comment]
Hello my fren,

Up to now, I think I only left with 1 main error during the compilation. Appreciate if you could provide some insights on this.

It seems like not able to locate the IContainer as a member of System::ComponentModel. I have added in all the reference related to System.ComponentModel and still not works :(

_Reference added for this^_
**System.ComponentModel.Composition
System.ComponentModel.DataAnnotations**

[compile error.txt](https://github.com/jnpl95/Timelapse/files/6911027/compile.error.txt)

The Visual studio version I using is 2019.

**Comment by felips113** [comment]
Hi, I think I am dumb enough to create a solution before that. 

I just notice that in the zip file there is a built in solution file. Please ignore my question above. However, I believe you compile this using a x86 windows right? because the way you define codecave (_asm) does not works in x64 windows. 

Appreciate if you share with me the workarounds or I should just compile it with x86 window.

**Comment by jnpl95** [comment]
Hey Felips,

Maplestory is a 32bit program so x86 is needed to inject the dll into the process. All the hacks depend on 32bit codecaves & memory edits since that's what maple is coded in.

I've left everything on the github for ppl who want to learn to Reverse Engineer maple and try out finding hacks on their own and stuff. If you run into any compile issues, part of the learning process is searching google and finding the answers for yourself which is also more fun as well.

The trainer should compile with no issues with the solution file I provided. It's coded for heavenms so there's no guarantee it'll work with online v83 servers, without map rush changes and specific things that each v83 server adds (like custom maps/items/quests).
Anyways just thought I'd respond just to let you know

**Comment by felips113** [comment]
Thank you! I have compiled it successfully after 2-3 days of google learning :)
